branch-defaults:
  deployment:
    environment: aws-es-kibana-node
environment-defaults:
  aws-es-kibana-node:
    branch: null
    repository: null
global:
  application_name: aws-es-kibana
  default_ec2_keyname: aws-eb-kibana
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on
    64bit Amazon Linux/4.5.1
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
